\Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['App\\Entity\\Question'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('App\\Entity\\Question')),
        (($f = &\Symfony\Component\VarExporter\Internal\Registry::$factories)['Doctrine\\ORM\\PersistentCollection'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Doctrine\\ORM\\PersistentCollection'))(),
        clone ($p['Doctrine\\Common\\Collections\\ArrayCollection'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\Common\\Collections\\ArrayCollection')),
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        clone ($p['DateTime'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('DateTime')),
        clone $p['DateTime'],
        clone $p['App\\Entity\\Question'],
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        clone $p['DateTime'],
        clone $p['DateTime'],
        clone $p['App\\Entity\\Question'],
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        clone $p['DateTime'],
        clone $p['DateTime'],
        clone $p['App\\Entity\\Question'],
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        clone $p['DateTime'],
        clone $p['DateTime'],
        clone $p['App\\Entity\\Question'],
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        clone $p['DateTime'],
        clone $p['DateTime'],
        clone $p['App\\Entity\\Question'],
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        clone $p['DateTime'],
        clone $p['DateTime'],
        clone $p['App\\Entity\\Question'],
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        $f['Doctrine\\ORM\\PersistentCollection'](),
        clone $p['Doctrine\\Common\\Collections\\ArrayCollection'],
        clone $p['DateTime'],
        clone $p['DateTime'],
    ],
    null,
    [
        'App\\Entity\\Question' => [
            'id' => [
                1,
                7 => 2,
                14 => 9,
                21 => 10,
                28 => 11,
                35 => 12,
                42 => 14,
            ],
            'answers' => [
                $o[1],
                7 => $o[8],
                14 => $o[15],
                21 => $o[22],
                28 => $o[29],
                35 => $o[36],
                42 => $o[43],
            ],
            'questionHistories' => [
                $o[3],
                7 => $o[10],
                14 => $o[17],
                21 => $o[24],
                28 => $o[31],
                35 => $o[38],
                42 => $o[45],
            ],
        ],
        'stdClass' => [
            'title' => [
                'tttt',
                7 => 'rrr',
                14 => 'rrttr',
                21 => 'rrttffr',
                28 => 'rrttFFFffr',
                35 => 'rrttFFFrrrrffr',
                42 => 'rrttFFFrffjjrrrffr',
            ],
            'promoted' => [
                true,
                7 => true,
                14 => true,
                21 => true,
                28 => true,
                35 => true,
                42 => true,
            ],
            'created' => [
                $o[5],
                7 => $o[12],
                14 => $o[19],
                21 => $o[26],
                28 => $o[33],
                35 => $o[40],
                42 => $o[47],
            ],
            'updated' => [
                $o[6],
                7 => $o[13],
                14 => $o[20],
                21 => $o[27],
                28 => $o[34],
                35 => $o[41],
                42 => $o[48],
            ],
            'status' => [
                'tttttt',
                7 => 'toto',
                14 => 'toto',
                21 => 'toto',
                28 => 'draft',
                35 => 'draft',
                42 => 'published',
            ],
            'date' => [
                5 => '2015-01-01 06:00:00.000000',
                '2015-01-01 00:00:00.000000',
                12 => '2020-03-13 17:17:33.000000',
                '2020-03-13 17:17:33.000000',
                19 => '2020-03-13 17:33:17.000000',
                '2020-03-13 17:33:17.000000',
                26 => '2020-03-13 17:39:14.000000',
                '2020-03-13 17:39:14.000000',
                33 => '2020-03-13 17:41:31.000000',
                '2020-03-13 17:41:31.000000',
                40 => '2020-03-13 18:14:35.000000',
                '2020-03-13 18:14:35.000000',
                47 => '2020-03-13 18:15:55.000000',
                '2020-03-14 10:06:39.000000',
            ],
            'timezone_type' => [
                5 => 3,
                3,
                12 => 3,
                3,
                19 => 3,
                3,
                26 => 3,
                3,
                33 => 3,
                3,
                40 => 3,
                3,
                47 => 3,
                3,
            ],
            'timezone' => [
                5 => 'UTC',
                'UTC',
                12 => 'UTC',
                'UTC',
                19 => 'UTC',
                'UTC',
                26 => 'UTC',
                'UTC',
                33 => 'UTC',
                'UTC',
                40 => 'UTC',
                'UTC',
                47 => 'UTC',
                'UTC',
            ],
        ],
        'Doctrine\\Common\\Collections\\AbstractLazyCollection' => [
            'collection' => [
                1 => $o[2],
                3 => $o[4],
                8 => $o[9],
                10 => $o[11],
                15 => $o[16],
                17 => $o[18],
                22 => $o[23],
                24 => $o[25],
                29 => $o[30],
                31 => $o[32],
                36 => $o[37],
                38 => $o[39],
                43 => $o[44],
                45 => $o[46],
            ],
        ],
        'Doctrine\\Common\\Collections\\ArrayCollection' => [
            'elements' => [
                2 => [],
                4 => [],
                9 => [],
                11 => [],
                16 => [],
                18 => [],
                23 => [],
                25 => [],
                30 => [],
                32 => [],
                37 => [],
                39 => [],
                44 => [],
                46 => [],
            ],
        ],
    ],
    [
        $o[0],
        $o[7],
        $o[14],
        $o[21],
        $o[28],
        $o[35],
        $o[42],
    ],
    [
        1 => 5,
        6,
        12,
        13,
        19,
        20,
        26,
        27,
        33,
        34,
        40,
        41,
        47,
        48,
    ]
)